### ISSUE TITLE
Problem when run cde_ddpg.py ?

### ISSUE THREAD

**Issue by ngthanhtin** [kshitij-ingale/kuka_robotic_arm_RL#1]
Hello, I ran into a problem that is like this:
episodes]Traceback (most recent call last):
  File "cde_ddpg.py", line 254, in <module>
    stats = ddpg.train(env)
  File "cde_ddpg.py", line 166, in train
    self.train_batch()
  File "cde_ddpg.py", line 202, in train_batch
    q_value = np.reshape(q_value, (1, ))
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 3 into shape (1,)
Could you please recommend how to fix this ?

**Comment by GoogleMike** [comment]
> Hello, I ran into a problem that is like this:
> episodes]Traceback (most recent call last):
> File "cde_ddpg.py", line 254, in 
> stats = ddpg.train(env)
> File "cde_ddpg.py", line 166, in train
> self.train_batch()
> File "cde_ddpg.py", line 202, in train_batch
> q_value = np.reshape(q_value, (1, ))
> File "<**array_function** internals>", line 6, in reshape
> File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
> return _wrapfunc(a, 'reshape', newshape, order=order)
> File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> File "/home/aioz-tin/TINNGUYEN/AICROWD/kuka_robotic_arm_RL/env_kuka/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> ValueError: cannot reshape array of size 3 into shape (1,)
> Could you please recommend how to fix this ?

Hello, I met the problem like this:
![11](https://user-images.githubusercontent.com/29306735/66326401-7a05b180-e95b-11e9-8eb8-3430c2abc1a1.png)

Have you met this?
Do you have any solutions?
